# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Teo Boley
email: teo@teoboley.com
description: > # this means to ignore newlines until "baseurl:"
  Fonts BEYNO and Bonkers used in this site were created by Fabian Korn.  Check out his Behance and give him some love!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.teoboley.com" # the base hostname & protocol for your site
github_username:  teoboley
paginate: 10

include: [
  "_pages"
]

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "package.json",
  "_dev",
  "gulpfile.js",
  "teoboley.com.sublime-project",
  "teoboley.com.sublime-workspace"
]

collections:
  projects:
    output: true
    permalink: /portfolio/:path/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: projects
    values:
      layout: project

# Build settings
markdown: kramdown